language: node_js

node_js:
  - '10'

cache: npm

script:
  - npm test

jobs:
  include:
    - stage: docs publish
      node_js: '10'
      script: npm run build:docs
      deploy:
        provider: pages
        skip-cleanup: true
        github-token: $GITHUB_TOKEN
        target-branch: gh-pages
        keep-history: true
        local-dir: build/
        on:
          branch: master
    - stage: npm release
      node_js: '10'
      script: npm run build:lib
      before_deploy: cd lib
      deploy:
        provider: npm
        skip-cleanup: true
        email: $NPM_EMAIL
        api_key: $NPM_TOKEN
        tag: latest
        on:
          branch: master
          tags: true
