language: node_js

node_js:
  - '12'

cache: npm

jobs:
  include:
    - stage: test
      script: npm run lint

    - stage: build_and_deploy_docs_next
      if: branch = master
      script: REPO_ENV=next npm run build:docs
      deploy:
        provider: surge
        project: storybook-static/
        domain: $DOCS_URL_NEXT
        skip_cleanup: true
        on:
          branch: master

    - stage: build_and_deploy_docs_tagged_release
      if: tag IS present
      before_script: if [[ ! -z "$DOCS_URL_RELEASE" ]]; then echo "$DOCS_URL_RELEASE" > static/CNAME; else false; fi
      script: REPO_ENV=release npm run build:docs
      deploy:
        provider: pages
        skip-cleanup: true
        github-token: $GITHUB_TOKEN
        target-branch: gh-pages
        keep-history: true
        local-dir: storybook-static/
        on:
          tags: true

    - stage: build_and_deploy_lib_tagged_release
      if: tag IS present
      script: REPO_ENV=release npm run build:lib
      before_deploy: cd lib
      deploy:
        provider: npm
        skip-cleanup: true
        email: $NPM_EMAIL
        api_key: $NPM_TOKEN
        tag: latest
        on:
          tags: true
