language: node_js

node_js:
  - 'lts/*'

cache:
  directories:
    - 'node_modules'

install:
  - npm install
  - npm run build
  - npm run docs:build

script:
  - npm test

deploy:
  - provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    target-branch: gh-pages
    keep-history: true
    local-dir: docs/
    on:
      branch: master
  - provider: npm
    skip-cleanup: true
    email: $NPM_EMAIL
    api_key: $NPM_TOKEN
    tag: latest
    on:
      tags: true
