on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    name: Deploy alys@next to Firebase Hosting
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Lint and build
        run: |
          npm ci
          npm run lint
          npm run build:docs
        env:
          STORYBOOK_DEMO_VIDEOS_BASE_URL: ${{ secrets.STORYBOOK_DEMO_VIDEOS_BASE_URL }}
      - name: Install Firebase CLI and deploy
        run: |
          npm install -g firebase-tools
          firebase deploy --only hosting:next --token ${{ secrets.FIREBASE_TOKEN }}
